var Reflux = require('reflux');

module.exports = Reflux.createActions([
  'login',
  'authenticate',
  'logout',
  'signup',
  'submitComment',
  'submitReply',
  'fetchLesson',
  'lessonTimepoint',
  'updateUser',
  'deleteComment',
  'likeComment',
  'unlikeComment',
  'starComment',
  'likeReply',
  'unlikeReply',
  'starReply',
  'deleteReply',
  'createLesson',
  'sendLesson',
  'getUser',
  'createExercise',
  'followLesson',
  'togglePublish',
  'publish',
  'setVideoDuration',
  'deleteLesson',
  'triggerConfigStore',
  'triggerLessonStore',
  'updateExercise',
  'deleteExercise',
  'submitExerciseResult'
]);
